/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/language`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/terms-acceptance`; params?: Router.UnknownInputParams; } | { pathname: `/terms-intro`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/gestion/OperationItem`; params?: Router.UnknownInputParams; } | { pathname: `/info-client/CardHistory`; params?: Router.UnknownInputParams; } | { pathname: `/info-client/CardOperations`; params?: Router.UnknownInputParams; } | { pathname: `/info-client/Tabs`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/gestion/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/info-client/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/language`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/terms-acceptance`; params?: Router.UnknownOutputParams; } | { pathname: `/terms-intro`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/gestion/OperationItem`; params?: Router.UnknownOutputParams; } | { pathname: `/info-client/CardHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/info-client/CardOperations`; params?: Router.UnknownOutputParams; } | { pathname: `/info-client/Tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/gestion/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/info-client/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/language${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/terms-acceptance${`?${string}` | `#${string}` | ''}` | `/terms-intro${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/gestion/OperationItem${`?${string}` | `#${string}` | ''}` | `/info-client/CardHistory${`?${string}` | `#${string}` | ''}` | `/info-client/CardOperations${`?${string}` | `#${string}` | ''}` | `/info-client/Tabs${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/language`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/terms-acceptance`; params?: Router.UnknownInputParams; } | { pathname: `/terms-intro`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/gestion/OperationItem`; params?: Router.UnknownInputParams; } | { pathname: `/info-client/CardHistory`; params?: Router.UnknownInputParams; } | { pathname: `/info-client/CardOperations`; params?: Router.UnknownInputParams; } | { pathname: `/info-client/Tabs`; params?: Router.UnknownInputParams; } | `/+not-found` | `/gestion/${Router.SingleRoutePart<T>}` | `/info-client/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/gestion/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/info-client/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
